// Aluno : Nuno Guerra - RA : a2706504
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormRelProdutos extends javax.swing.JFrame {
    
    private Produto p1 = new Produto();
    private Pedido p = new Pedido();
    private Atendente atendenteVenda;
    private Cliente clienteVenda;
    private FormVenda formVendaOrigem;
    private BdItens gp = BdItens.geraGerProdutos();
    private float precoTotal = 0;
    private static FormRelProdutos relProdUnic;
    
    private FormRelProdutos() {
        initComponents();
    }
    
    // Método Singleton
    public static FormRelProdutos geraRelProd(){
        if(relProdUnic == null){
            relProdUnic = new FormRelProdutos();
        }
        return relProdUnic;
    }

    public void setDadosVenda(Atendente atendente, Cliente cliente, FormVenda form) {
        this.atendenteVenda = atendente;
        this.clienteVenda = cliente;
        this.formVendaOrigem = form;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelProdutos = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        rtProdutosDisponiveis = new javax.swing.JLabel();
        btFinalizarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbRelProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Preço"
            }
        ));
        tbRelProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelProdutos);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtProdutosDisponiveis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtProdutosDisponiveis.setText("Produtos Disponiveis");

        btFinalizarVenda.setText("Finalizar Venda");
        btFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btFinalizarVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rtProdutosDisponiveis)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtProdutosDisponiveis)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btFinalizarVenda))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lisTab();
    }//GEN-LAST:event_formWindowActivated

    private void tbRelProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelProdutosMouseClicked
        selecTab();
    }//GEN-LAST:event_tbRelProdutosMouseClicked

    private void btFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarVendaActionPerformed
        formVendaOrigem.fimVenda(atendenteVenda, clienteVenda, p.getProduto(), precoTotal);
        formVendaOrigem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btFinalizarVendaActionPerformed
    
    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbRelProdutos.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Produto p : gp.getBdProd()){
            modTab.insertRow(posLin, new Object[]{p.getNome(), p.getPreco()});
            posLin++;
        }
    }
    
    public void selecTab(){
        int posLin = tbRelProdutos.getSelectedRow();
        if (posLin >= 0){
            String nomeProduto = tbRelProdutos.getValueAt(posLin, 0).toString();
            
            Produto produtoSelecionado = null;
            for (Produto p : gp.getBdProd()){
                if (p.getNome().equals(nomeProduto)){
                    produtoSelecionado = p;
                    precoTotal += produtoSelecionado.getPreco();
                }
            }
            
            if (produtoSelecionado != null){
                p.adicionarProduto(produtoSelecionado);
                JOptionPane.showMessageDialog(
                        null,
                        "Produto adicionado com sucesso!",
                        "Inserção de produto",
                        JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "ERRO : Produto não encontrado!",
                        "Inserção de produto",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
            
            JOptionPane.showMessageDialog(
                    null,
                    "Clique em 'Finalizar Venda' para concluir!",
                    "Sistema de vendas",
                    JOptionPane.INFORMATION_MESSAGE
            );
        }   
    }
    
    public float getPrecoTotal(){
        return precoTotal;
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida do Sistema",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizarVenda;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtProdutosDisponiveis;
    private javax.swing.JTable tbRelProdutos;
    // End of variables declaration//GEN-END:variables
}
