// Aluno : Nuno Guerra - RA : a2706504
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class FormCadastroCliente extends javax.swing.JFrame {
    
    private Cliente c1 = new Cliente();
    private BdPessoa gc = BdPessoa.geraBdPessoa();
    private static FormCadastroCliente cadCliUnic;
   
    private FormCadastroCliente() {
        initComponents();
    }
    
    // Método Singleton
    public static FormCadastroCliente geraCadCli(){
        if(cadCliUnic == null){
            cadCliUnic = new FormCadastroCliente();
        }
        return cadCliUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCadastroCliente = new javax.swing.JLabel();
        rtCpf = new javax.swing.JLabel();
        rtTelefone = new javax.swing.JLabel();
        rtNome = new javax.swing.JLabel();
        rtPreferencia = new javax.swing.JLabel();
        cxPreferencia = new javax.swing.JTextField();
        cxNome = new javax.swing.JTextField();
        cxTelefone = new javax.swing.JTextField();
        cxCpf = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterarPreferencia = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtCadastroCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtCadastroCliente.setText("Cadastro Cliente");

        rtCpf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtCpf.setText("CPF................. :");

        rtTelefone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtTelefone.setText("TELEFONE...... :");

        rtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtNome.setText("NOME............ :");

        rtPreferencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtPreferencia.setText("PREFERÊNCIA :");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterarPreferencia.setText("Alterar Preferência");
        btAlterarPreferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarPreferenciaActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(rtCadastroCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btInserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterarPreferencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluir)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rtPreferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cxPreferencia)
                    .addComponent(cxNome)
                    .addComponent(cxTelefone)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtCadastroCliente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTelefone)
                    .addComponent(cxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPreferencia)
                    .addComponent(cxPreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(btConsultar)
                    .addComponent(btAlterarPreferencia)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        try {
            insCliente();
        } catch (PreferenciaNumException ex) {
            Logger.getLogger(FormCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultCliente();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarPreferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarPreferenciaActionPerformed
        try {
            alterarPreferencia();
        } catch (PreferenciaNumException ex) {
            Logger.getLogger(FormCadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterarPreferenciaActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirCliente();
    }//GEN-LAST:event_btExcluirActionPerformed

    public void excluirCliente(){
        c1 = new Cliente();
        
        c1.setCpf(cxCpf.getText());
        
        c1 = gc.delCliCpf(c1);
        
        if(c1 == null){
            JOptionPane.showMessageDialog(
                    null,
                    "Cliente apagado com sucesso!",
                    "Exclusão de cliente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : CPF não encontrado",
                    "Exclusão de cliente",
                    JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
    }
    
    public void alterarPreferencia() throws PreferenciaNumException{
        try {
        c1 = new Cliente();
        
        c1.setCpf(cxCpf.getText());
        
        c1 = gc.atualizaCliCpf(c1);
        
        if(c1 != null){
            cxNome.setText(c1.getNome());
            cxCpf.setText(c1.getCpf());
            cxTelefone.setText(c1.getTelefone());
            cxPreferencia.setText(c1.getPreferencia());
            JOptionPane.showMessageDialog(
                    null,
                    "Cliente encontrado, verifique os dados :",
                    "Alteração de cliente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : CPF não encontrado!",
                    "Alteração de cliente",
                    JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
        }//fim try
        
        catch(PreferenciaNumException pne){
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : A preferencia deve conter apenas letras!",
                    "Alteração de Cliente",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }// fim alterarPreferencia
    
    public void consultCliente(){
        c1 = new Cliente();
        
        c1.setCpf(cxCpf.getText());
        
        c1 = gc.consCliCpf(c1);
        
        if(c1 != null){
            cxNome.setText(c1.getNome());
            cxCpf.setText(c1.getCpf());
            cxTelefone.setText(c1.getTelefone());
            cxPreferencia.setText(c1.getPreferencia());
            
            JOptionPane.showMessageDialog(
                    null,
                    "Data de cadastro : "+c1.getDataCadastro(),
                    "Consulta de Cliente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
            JOptionPane.showMessageDialog(
                    null,
                    "Confirme os dados!",
                    "Consulta de Cliente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Não existe cliente com esse CPF!",
                    "Consulta de cliente",
                    JOptionPane.ERROR_MESSAGE
            ); 
            cxCpf.setText("");
            cxCpf.requestFocus();
        } 
    } //fim consultCliente
    
    public void insCliente() throws PreferenciaNumException{
       try {
       c1 = new Cliente();
       
       c1.setCpf(cxCpf.getText());
       c1.setNome(cxNome.getText());
       c1.setTelefone(cxTelefone.getText());
       c1.setPreferencia(cxPreferencia.getText());
       
       c1 = gc.insCli(c1);
       
       if(c1 != null){
            JOptionPane.showMessageDialog(
                    null,
                    "Cliente cadastrado com sucesso!",
                    "Cadastro de Cliente",
                    1
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Já existe um cliente com esse CPF!",
                    "Cadastro de Cliente",
                    JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
       }//fim try
       
       catch(PreferenciaNumException pne){
           JOptionPane.showMessageDialog(
                    null,
                    "ERRO : A preferencia deve conter apenas letras!",
                    "Cadastro de Cliente",
                    JOptionPane.ERROR_MESSAGE
            );
           cxPreferencia.setText("");
           cxPreferencia.requestFocus();
       }
    } //fim insCliente
    
    public void limpar(){
        cxNome.setText("");
        cxCpf.setText("");
        cxTelefone.setText("");
        cxPreferencia.setText("");
        cxCpf.requestFocus();
    }
    
    public void sair(){
       int resp = JOptionPane.showConfirmDialog(
               null,
               "Deseja realmente sair?",
               "Siada do sistema",
               JOptionPane.YES_NO_OPTION
       ); 
       if (resp == 0){
           dispose();
       }
    } // fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarPreferencia;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPreferencia;
    private javax.swing.JTextField cxTelefone;
    private javax.swing.JLabel rtCadastroCliente;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtPreferencia;
    private javax.swing.JLabel rtTelefone;
    // End of variables declaration//GEN-END:variables
}
