// Aluno : Nuno Guerra - RA : a2706504
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class FormVenda extends javax.swing.JFrame {
    
    private BdPessoa gp = BdPessoa.geraBdPessoa();
    private FormRelProdutos rp = FormRelProdutos.geraRelProd();
    private int quantidadeCompra = 0;
    private static FormVenda cadVendaUnic;
    
    private FormVenda() {
        initComponents();
    }
    
    // Método Singleton
    public static FormVenda geraCadVenda(){
        if(cadVendaUnic == null){
            cadVendaUnic = new FormVenda();
        }
        return cadVendaUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtVenda = new javax.swing.JLabel();
        rtAtendente = new javax.swing.JLabel();
        rtCliente = new javax.swing.JLabel();
        cxNomeAtend = new javax.swing.JTextField();
        cxNomeCliente = new javax.swing.JTextField();
        Sair = new javax.swing.JButton();
        rtIdCompra = new javax.swing.JLabel();
        cxIdCompra = new javax.swing.JTextField();
        rtValorTotal = new javax.swing.JLabel();
        cxValorTotal = new javax.swing.JTextField();
        rtDataCompra = new javax.swing.JLabel();
        cxDataCompra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rtVenda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtVenda.setText("Venda");

        rtAtendente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtAtendente.setText("Atendente..... :");

        rtCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtCliente.setText("Cliente........... :");

        cxNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeClienteActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        rtIdCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtIdCompra.setText("ID da Compra :");

        cxIdCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxIdCompraActionPerformed(evt);
            }
        });

        rtValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtValorTotal.setText("Valor Total.... :");

        rtDataCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtDataCompra.setText("Data Compra :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Sair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(rtVenda))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rtIdCompra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rtAtendente)
                                            .addComponent(rtCliente))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cxNomeCliente)
                                            .addComponent(cxNomeAtend)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(rtDataCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rtValorTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cxValorTotal)
                                            .addComponent(cxDataCompra))))))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtVenda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtAtendente)
                    .addComponent(cxNomeAtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCliente)
                    .addComponent(cxNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtIdCompra)
                    .addComponent(cxIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtValorTotal)
                    .addComponent(cxValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDataCompra)
                    .addComponent(cxDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(Sair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        inicioVenda();
    }//GEN-LAST:event_formWindowOpened

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        sair();
    }//GEN-LAST:event_SairActionPerformed

    private void cxNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeClienteActionPerformed

    private void cxIdCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxIdCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxIdCompraActionPerformed

    public void fimVenda(Atendente atend, Cliente cli, List<Produto> produtos, float precoTotal){
        Compra novaCompra = new Compra();
        novaCompra.setIdCompra(quantidadeCompra + 1);
        novaCompra.setCliente(cli);
        novaCompra.setValorTotal(precoTotal);
        novaCompra.setDataCompra(LocalDate.now());
        novaCompra.setAtendente(atend);
        novaCompra.setProdutos(produtos);
        atend.setTotalVendas(atend.getTotalVendas() + 1);
        atend.setValorTotalVendas(FormRelProdutos.geraRelProd().getPrecoTotal());
        
        JOptionPane.showMessageDialog(
                null,
                "Venda concluida com sucesso! verifique os dados",
                "Sistema de venda",
                JOptionPane.INFORMATION_MESSAGE
        );
        
        cxNomeAtend.setText(atend.getNome());
        cxNomeCliente.setText(cli.getNome());
        cxIdCompra.setText(Integer.toString(novaCompra.getIdCompra()));
        cxValorTotal.setText(Float.toString(novaCompra.getValorTotal()));
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        cxDataCompra.setText(novaCompra.getDataCompra().format(formato));
        
        quantidadeCompra++;
    }
    
    public void inicioVenda(){
        String cpf_a = JOptionPane.showInputDialog(
                null,
                "Informe o CPF do atendente : ",
                "Sistema de venda",
                JOptionPane.INFORMATION_MESSAGE
        );
        
        for (Atendente a : gp.getBdAtend()){
            if (cpf_a.equals(a.getCpf())){
                Atendente atendVenda = a;
                
                String cpf_c = JOptionPane.showInputDialog(
                        null,
                        "Informe o CPF do Cliente : ",
                        "Sistema de venda",
                        JOptionPane.INFORMATION_MESSAGE
                );
                
                for (Cliente c : gp.getBdCli()){
                    if (cpf_c.equals(c.getCpf())){
                        
                        Cliente clienteVenda = c;
                        
                        JOptionPane.showMessageDialog(
                                null,
                                "Atendente e cliente encontrados!",
                                "Sistema de venda",
                                JOptionPane.INFORMATION_MESSAGE
                        );
                        
                        FormRelProdutos relProd = FormRelProdutos.geraRelProd();
                        relProd.setDadosVenda(atendVenda, clienteVenda, this);
                        relProd.setVisible(true);
                        this.setVisible(false);
                        
                        JOptionPane.showMessageDialog(
                                null,
                                "Clique em um produto para adicioná-lo!",
                                "Sistema de venda",
                                JOptionPane.INFORMATION_MESSAGE
                        );
                        
                    }// fim ifCliente
                    else {
                        JOptionPane.showMessageDialog(
                                null,
                                "ERRO : Não existe cliente com esse CPF!",
                                "Sistema de vendas",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                }// fim ForCliente
            } else {
                JOptionPane.showMessageDialog(
                        null,
                        "ERRO : Não existe atendente com esse CPF!",
                        "Sistema de vendas",
                        JOptionPane.ERROR_MESSAGE
                );
            } // fim ifAtendente
        }// fim ForAtendente
    }// fim inicioVenda
    
    public void sair(){
       int resp = JOptionPane.showConfirmDialog(
               null,
               "Deseja realmente sair?",
               "Siada do sistema",
               JOptionPane.YES_NO_OPTION
       ); 
       if (resp == 0){
           dispose();
       }
    } // fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JTextField cxDataCompra;
    private javax.swing.JTextField cxIdCompra;
    private javax.swing.JTextField cxNomeAtend;
    private javax.swing.JTextField cxNomeCliente;
    private javax.swing.JTextField cxValorTotal;
    private javax.swing.JLabel rtAtendente;
    private javax.swing.JLabel rtCliente;
    private javax.swing.JLabel rtDataCompra;
    private javax.swing.JLabel rtIdCompra;
    private javax.swing.JLabel rtValorTotal;
    private javax.swing.JLabel rtVenda;
    // End of variables declaration//GEN-END:variables
}
