// Aluno : Nuno Guerra - RA : a2706504
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormRelCafe extends javax.swing.JFrame {

    private Cafe ca1 = new Cafe();
    private BdProdutos gca = BdProdutos.geraBdProdutos();
    private static FormRelCafe relCafeUnic;
    
    private FormRelCafe() {
        initComponents();
    }
    
    // Método Singleton
    public static FormRelCafe geraRelCafe(){
        if(relCafeUnic == null){
            relCafeUnic = new FormRelCafe();
        }
        return relCafeUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelCafe = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        rtRelCafe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbRelCafe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Tamanho", "Tipo", "Intensidade"
            }
        ));
        tbRelCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelCafeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelCafe);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtRelCafe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtRelCafe.setText("Relatório de Cafés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtRelCafe)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtRelCafe)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lisTab();
    }//GEN-LAST:event_formWindowActivated

    private void tbRelCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelCafeMouseClicked
        selecTab();
    }//GEN-LAST:event_tbRelCafeMouseClicked

    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbRelCafe.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Cafe ca : gca.getBdCafe()){
            modTab.insertRow(posLin, new Object[]{ca.getNome(), ca.getPreco(), ca.getTamanho(), ca.getTipo(), ca.getIntensidade()});
            posLin++;
        }
    }
    
    public void selecTab(){
        int posLin = tbRelCafe.getSelectedRow();
        if (posLin >= 0) {
            String valLin = 
                "Nome: " + tbRelCafe.getValueAt(posLin, 0) + "\n" +
                "Preço: " + tbRelCafe.getValueAt(posLin, 1) + "\n" +
                "Tamanho: " + tbRelCafe.getValueAt(posLin, 2) + "\n" +
                "Tipo: " + tbRelCafe.getValueAt(posLin, 3) + "\n" +
                "Intensidade: " + tbRelCafe.getValueAt(posLin, 4);

            JOptionPane.showMessageDialog(null, valLin, "Dados Selecionados", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void sair(){
       int resp = JOptionPane.showConfirmDialog(
               null,
               "Deseja realmente sair?",
               "Siada do sistema",
               JOptionPane.YES_NO_OPTION
       ); 
       if (resp == 0){
           dispose();
       }
    } // fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelCafe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtRelCafe;
    private javax.swing.JTable tbRelCafe;
    // End of variables declaration//GEN-END:variables
}
