// Aluno : Nuno Guerra - RA : a2706504
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormRelCliente extends javax.swing.JFrame {
    
    private Cliente c1 = new Cliente();
    private BdPessoa gc = BdPessoa.geraBdPessoa();
    private static FormRelCliente relClienteUnic;
    
    private FormRelCliente() {
        initComponents();
    }
    
    // Método Singleton
    public static FormRelCliente geraRelCliente(){
        if(relClienteUnic == null){
            relClienteUnic = new FormRelCliente();
        }
        return relClienteUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelCliente = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        rtRelCliente = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbRelCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "CPF", "Preferência", "Data Cadastro"
            }
        ));
        tbRelCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelCliente);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtRelCliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtRelCliente.setText("Relatório de Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtRelCliente)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtRelCliente)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lisTab();
    }//GEN-LAST:event_formWindowActivated

    private void tbRelClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelClienteMouseClicked
        selecTab();
    }//GEN-LAST:event_tbRelClienteMouseClicked

    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbRelCliente.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Cliente c : gc.getBdCli()){
            modTab.insertRow(posLin, new Object[]{c.getNome(), c.getTelefone(), c.getCpf(), c.getPreferencia(), c.getDataCadastro()});
            posLin++;
        }
    }
    
    public void selecTab(){
        int posLin = tbRelCliente.getSelectedRow();
        if (posLin >= 0) {
            String valLin = 
                "Nome: " + tbRelCliente.getValueAt(posLin, 0) + "\n" +
                "Telefone: " + tbRelCliente.getValueAt(posLin, 1) + "\n" +
                "CPF: " + tbRelCliente.getValueAt(posLin, 2) + "\n" +
                "Preferência: " + tbRelCliente.getValueAt(posLin, 3) + "\n" +
                "Data Cadastro: " + tbRelCliente.getValueAt(posLin, 4);

            JOptionPane.showMessageDialog(null, valLin, "Dados Selecionados", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida do Sistema",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtRelCliente;
    private javax.swing.JTable tbRelCliente;
    // End of variables declaration//GEN-END:variables
}
