// Versão NetBeans : 25
// Aluno : Nuno Guerra - RA : a2706504

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCafeteria = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itMnCadAtend = new javax.swing.JMenuItem();
        itMnCadCli = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itMnCadCafe = new javax.swing.JMenuItem();
        itMnCadBolo = new javax.swing.JMenuItem();
        itMnCadSalg = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itMnRelAtend = new javax.swing.JMenuItem();
        itMnRelCli = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itMnRelCafe = new javax.swing.JMenuItem();
        itMnRelBolo = new javax.swing.JMenuItem();
        itMnRelSalg = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        itMnVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtCafeteria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtCafeteria.setText("CAFETERIA");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setText("`-----------'");

        jLabel2.setText("|                   /");

        jLabel3.setText("|                  |]");

        jLabel4.setText(".....................");

        jLabel5.setText("    ) )  ");

        jLabel6.setText("( (");

        jMenu1.setText("Cadastros");

        itMnCadAtend.setText("Cadastro Atendente...");
        itMnCadAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadAtendActionPerformed(evt);
            }
        });
        jMenu1.add(itMnCadAtend);

        itMnCadCli.setText("Cadastro Cliente...");
        itMnCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCliActionPerformed(evt);
            }
        });
        jMenu1.add(itMnCadCli);

        jMenu3.setText("Cadastro Produto");

        itMnCadCafe.setText("Cadastro Café...");
        itMnCadCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadCafeActionPerformed(evt);
            }
        });
        jMenu3.add(itMnCadCafe);

        itMnCadBolo.setText("Cadastro Bolo...");
        itMnCadBolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadBoloActionPerformed(evt);
            }
        });
        jMenu3.add(itMnCadBolo);

        itMnCadSalg.setText("Cadastro Salgado...");
        itMnCadSalg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadSalgActionPerformed(evt);
            }
        });
        jMenu3.add(itMnCadSalg);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");

        itMnRelAtend.setText("Relatório Atendente...");
        itMnRelAtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelAtendActionPerformed(evt);
            }
        });
        jMenu2.add(itMnRelAtend);

        itMnRelCli.setText("Relatório Cliente...");
        itMnRelCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelCliActionPerformed(evt);
            }
        });
        jMenu2.add(itMnRelCli);

        jMenu4.setText("Relatório Produtos");

        itMnRelCafe.setText("Relatório Café...");
        itMnRelCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelCafeActionPerformed(evt);
            }
        });
        jMenu4.add(itMnRelCafe);

        itMnRelBolo.setText("Relatório Bolo...");
        itMnRelBolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelBoloActionPerformed(evt);
            }
        });
        jMenu4.add(itMnRelBolo);

        itMnRelSalg.setText("Relatório Salgado");
        itMnRelSalg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelSalgActionPerformed(evt);
            }
        });
        jMenu4.add(itMnRelSalg);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Vendas");

        itMnVenda.setText("Vender...");
        itMnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnVendaActionPerformed(evt);
            }
        });
        jMenu5.add(itMnVenda);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addGap(5, 5, 5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(rtCafeteria)))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(rtCafeteria)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void itMnCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCliActionPerformed
        FormCadastroCliente.geraCadCli().setVisible(true);
    }//GEN-LAST:event_itMnCadCliActionPerformed

    private void itMnCadAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadAtendActionPerformed
        FormCadastroAtendente.geraCadAtend().setVisible(true);
    }//GEN-LAST:event_itMnCadAtendActionPerformed

    private void itMnRelAtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelAtendActionPerformed
        FormRelAtendente.geraRelAtend().setVisible(true);
    }//GEN-LAST:event_itMnRelAtendActionPerformed

    private void itMnRelCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelCliActionPerformed
        FormRelCliente.geraRelCliente().setVisible(true);
    }//GEN-LAST:event_itMnRelCliActionPerformed

    private void itMnCadCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadCafeActionPerformed
        FormCadastroCafe.geraCadCafe().setVisible(true);
    }//GEN-LAST:event_itMnCadCafeActionPerformed

    private void itMnCadBoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadBoloActionPerformed
        FormCadastroBolo.geraCadBolo().setVisible(true);
    }//GEN-LAST:event_itMnCadBoloActionPerformed

    private void itMnCadSalgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadSalgActionPerformed
        FormCadastroSalgado.geraCadSalg().setVisible(true);
    }//GEN-LAST:event_itMnCadSalgActionPerformed

    private void itMnRelCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelCafeActionPerformed
        FormRelCafe.geraRelCafe().setVisible(true);
    }//GEN-LAST:event_itMnRelCafeActionPerformed

    private void itMnRelBoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelBoloActionPerformed
        FormRelBolo.geraRelBolo().setVisible(true);
    }//GEN-LAST:event_itMnRelBoloActionPerformed

    private void itMnRelSalgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelSalgActionPerformed
        FormRelSalgado.geraRelSalgado().setVisible(true);
    }//GEN-LAST:event_itMnRelSalgActionPerformed

    private void itMnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnVendaActionPerformed
        FormVenda.geraCadVenda().setVisible(true);
    }//GEN-LAST:event_itMnVendaActionPerformed

    public void sair(){
       int resp = JOptionPane.showConfirmDialog(
               null,
               "Deseja realmente sair?",
               "Siada do sistema",
               JOptionPane.YES_NO_OPTION
       ); 
       if (resp == 0){
           dispose();
       }
    } // fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem itMnCadAtend;
    private javax.swing.JMenuItem itMnCadBolo;
    private javax.swing.JMenuItem itMnCadCafe;
    private javax.swing.JMenuItem itMnCadCli;
    private javax.swing.JMenuItem itMnCadSalg;
    private javax.swing.JMenuItem itMnRelAtend;
    private javax.swing.JMenuItem itMnRelBolo;
    private javax.swing.JMenuItem itMnRelCafe;
    private javax.swing.JMenuItem itMnRelCli;
    private javax.swing.JMenuItem itMnRelSalg;
    private javax.swing.JMenuItem itMnVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel rtCafeteria;
    // End of variables declaration//GEN-END:variables
}
