// Aluno : Nuno Guerra - RA : a2706504
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class FormCadastroAtendente extends javax.swing.JFrame {
    
    private Atendente a1 = new Atendente();
    private BdPessoa ga = BdPessoa.geraBdPessoa();
    private static FormCadastroAtendente cadAtendUnic;
  
    private FormCadastroAtendente() {
        initComponents();
    }
    
    // Método Singleton
    public static FormCadastroAtendente geraCadAtend(){
        if(cadAtendUnic == null){
            cadAtendUnic = new FormCadastroAtendente();
        }
        return cadAtendUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtNome = new javax.swing.JLabel();
        rtTelefone = new javax.swing.JLabel();
        rtCpf = new javax.swing.JLabel();
        rtSalario = new javax.swing.JLabel();
        rtBonus = new javax.swing.JLabel();
        rtTurno = new javax.swing.JLabel();
        cxTurno = new javax.swing.JTextField();
        cxBonus = new javax.swing.JTextField();
        cxSalario = new javax.swing.JTextField();
        cxCpf = new javax.swing.JTextField();
        cxTelefone = new javax.swing.JTextField();
        cxNome = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btInserir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterarSalario = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtNome.setText("NOME................... : ");

        rtTelefone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtTelefone.setText("TELEFONE............. : ");

        rtCpf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtCpf.setText("CPF........................ :");

        rtSalario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtSalario.setText("SALARIO............... :");

        rtBonus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtBonus.setText("BONUS.................. :");

        rtTurno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtTurno.setText("TURNO.................. :");

        cxSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSalarioActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro Atendente");

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterarSalario.setText("Alterar Salario");
        btAlterarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarSalarioActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rtBonus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rtTurno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cxTurno)
                                    .addComponent(cxBonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtTelefone)
                                .addGap(12, 12, 12)
                                .addComponent(cxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNome)
                                .addGap(12, 12, 12)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtSalario)
                                .addGap(12, 12, 12)
                                .addComponent(cxSalario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(cxCpf)))
                        .addGap(0, 54, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(0, 98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAlterarSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExcluir)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTelefone)
                    .addComponent(cxTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtSalario)
                    .addComponent(cxSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtBonus)
                    .addComponent(cxBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTurno)
                    .addComponent(cxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(btConsultar)
                    .addComponent(btAlterarSalario)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        try {
            insAtendente();
        } catch (SalarioMinException ex) {
            Logger.getLogger(FormCadastroAtendente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TurnoNumException ex) {
            Logger.getLogger(FormCadastroAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void cxSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSalarioActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
       consultAtendente();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarSalarioActionPerformed
        try {
            alterarSalario();
        } catch (SalarioMinException ex) {
            Logger.getLogger(FormCadastroAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAlterarSalarioActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirAtendente();
    }//GEN-LAST:event_btExcluirActionPerformed

    public void excluirAtendente(){
        a1 = new Atendente();
        
        a1.setCpf(cxCpf.getText());
        
        a1 = ga.delAtendCpf(a1);
        
        if(a1 == null){
            JOptionPane.showMessageDialog(
                    null,
                    "Atendente apagado com sucesso!",
                    "Exclusão de atendente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : CPF não encontrado",
                    "Exclusão de atendente",
                    JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
    }
    
    public void alterarSalario() throws SalarioMinException{
        try {
        a1 = new Atendente();
        
        a1.setCpf(cxCpf.getText());
        
        a1 = ga.atualizaAtendCpf(a1);
        
        if(a1 != null){
            cxNome.setText(a1.getNome());
            cxCpf.setText(a1.getCpf());
            cxTelefone.setText(a1.getTelefone());
            cxSalario.setText(Float.toString(a1.getSalario()));
            cxBonus.setText(Float.toString(a1.getBonus()));
            cxTurno.setText(a1.getTurno());
            JOptionPane.showMessageDialog(
                    null,
                    "Atendente encontrado, verifique os dados :",
                    "Alteração de atendente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : CPF não encontrado!",
                    "Alteração de atendente",
                    JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
        }// fim try
        
        catch(SalarioMinException sme){
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : O salario deve ser maior que o salario minimo (1.518,00)",
                    "Cadastro de Atendente",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
        catch(NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : O valor deve ser um numero!",
                    "Erro de dados",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
    }
    
    public void consultAtendente(){
        a1 = new Atendente();
        
        a1.setCpf(cxCpf.getText());
        
        a1 = ga.consAtendCpf(a1);
        
        if(a1 != null){
            cxNome.setText(a1.getNome());
            cxCpf.setText(a1.getCpf());
            cxTelefone.setText(a1.getTelefone());
            cxSalario.setText(Float.toString(a1.getSalario()));
            cxBonus.setText(Float.toString(a1.getBonus()));
            cxTurno.setText(a1.getTurno());
            
            JOptionPane.showMessageDialog(
                    null,
                    "Salário total : "+a1.salarioTotal(), //interfaçe
                    "Consulta de Atendente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            
            JOptionPane.showMessageDialog(
                    null,
                    "Confirme os dados!",
                    "Consulta de Atendente",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
          JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Não existe atendente com esse CPF!",
                    "Consulta de Atendente",
                    JOptionPane.ERROR_MESSAGE
            ); 
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
    } // fim consulAtendente
    
    public void insAtendente() throws SalarioMinException, TurnoNumException{
        try{
        a1 = new Atendente();
        
        a1.setNome(cxNome.getText());
        a1.setCpf(cxCpf.getText());
        a1.setTelefone(cxTelefone.getText());
        a1.setSalario(Float.parseFloat(cxSalario.getText()));
        a1.setBonus(Float.parseFloat(cxBonus.getText()));
        a1.setTurno(cxTurno.getText());
        a1 = ga.insAtend(a1);
        
        if(a1 != null){
            JOptionPane.showMessageDialog(
                    null,
                    "Atendente cadastrado com sucesso!",
                    "Cadastro de Atendente",
                    1
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Já existe um atendente com esse CPF!",
                    "Cadastro de Atendente",
                    JOptionPane.ERROR_MESSAGE
            );
            cxCpf.setText("");
            cxCpf.requestFocus();
        }
        }//fim try
        
        catch(SalarioMinException sme){
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : O salario deve ser maior que o salario minimo (1.518,00)",
                    "Cadastro de Atendente",
                    JOptionPane.ERROR_MESSAGE
            );
            cxSalario.setText("");
            cxSalario.requestFocus();
        }
        
        catch(TurnoNumException tne){
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : O turno deve conter apenas letras!",
                    "Erro de dados",
                    JOptionPane.ERROR_MESSAGE
            );
            cxTurno.setText("");
            cxTurno.requestFocus();
        }
        
        catch(NumberFormatException nfe) {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : O valor deve ser um numero!",
                    "Erro de dados",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
    }// fim insAtendente
    
    public void limpar(){
        cxNome.setText("");
        cxCpf.setText("");
        cxTelefone.setText("");
        cxSalario.setText("");
        cxBonus.setText("");
        cxTurno.setText("");
        cxCpf.requestFocus();
    }
    
    public void sair(){
       int resp = JOptionPane.showConfirmDialog(
               null,
               "Deseja realmente sair?",
               "Siada do sistema",
               JOptionPane.YES_NO_OPTION
       ); 
       if (resp == 0){
           dispose();
       }
    } // fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarSalario;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxBonus;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSalario;
    private javax.swing.JTextField cxTelefone;
    private javax.swing.JTextField cxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rtBonus;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSalario;
    private javax.swing.JLabel rtTelefone;
    private javax.swing.JLabel rtTurno;
    // End of variables declaration//GEN-END:variables
}
