// Aluno : Nuno Guerra - RA : a2706504
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormRelAtendente extends javax.swing.JFrame {
    
    private Atendente a1 = new Atendente();
    private BdPessoa ga = BdPessoa.geraBdPessoa();
    private static FormRelAtendente relAtendUnic;
    
    private FormRelAtendente() {
        initComponents();
    }
    
    // Método Singleton
    public static FormRelAtendente geraRelAtend(){
        if(relAtendUnic == null){
            relAtendUnic = new FormRelAtendente();
        }
        return relAtendUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelAtend = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        rtRelAtend = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbRelAtend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Telefone", "CPF", "Salário", "Bônus", "Turno", "Total Vendas", "Valor total Vendas"
            }
        ));
        tbRelAtend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelAtendMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelAtend);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtRelAtend.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtRelAtend.setText("Relatório de Atendentes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtRelAtend)
                .addGap(268, 268, 268))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtRelAtend)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lisTab();
    }//GEN-LAST:event_formWindowActivated

    private void tbRelAtendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelAtendMouseClicked
        selecTab();
    }//GEN-LAST:event_tbRelAtendMouseClicked

    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbRelAtend.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Atendente a : ga.getBdAtend()){
            modTab.insertRow(posLin, new Object[]{a.getNome(), a.getTelefone(), a.getCpf(), a.getSalario(), a.getBonus(), a.getTurno(), a.getTotalVendas(), a.getValorTotalVendas()});
            posLin++;
        }
    }
    
    public void selecTab(){
        int posLin = tbRelAtend.getSelectedRow();
        if (posLin >= 0) {
            String valLin = 
                "Nome: " + tbRelAtend.getValueAt(posLin, 0) + "\n" +
                "Telefone: " + tbRelAtend.getValueAt(posLin, 1) + "\n" +
                "CPF: " + tbRelAtend.getValueAt(posLin, 2) + "\n" +
                "Salário: " + tbRelAtend.getValueAt(posLin, 3) + "\n" +
                "Bônus: " + tbRelAtend.getValueAt(posLin, 4) + "\n" +
                "Turno: " + tbRelAtend.getValueAt(posLin, 5) + "\n" +
                "Total Vendas: " + tbRelAtend.getValueAt(posLin, 6) + "\n" +
                "Valor Total Vendas: " + tbRelAtend.getValueAt(posLin, 7);

            JOptionPane.showMessageDialog(
                    null, 
                    valLin, 
                    "Dados Selecionados", 
                    JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "Saida do Sistema",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtRelAtend;
    private javax.swing.JTable tbRelAtend;
    // End of variables declaration//GEN-END:variables
}
