// Aluno : Nuno Guerra - RA : a2706504
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormRelBolo extends javax.swing.JFrame {

    private Bolo b = new Bolo();
    private BdProdutos gb = BdProdutos.geraBdProdutos();
    private static FormRelBolo relBoloUnic;
    
    private FormRelBolo() {
        initComponents();
    }
    
    // Método Singleton
    public static FormRelBolo geraRelBolo(){
        if(relBoloUnic == null){
            relBoloUnic = new FormRelBolo();
        }
        return relBoloUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelBolo = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        rtRelBolo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbRelBolo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Sabor", "Peso por Fatia", "Cobertura"
            }
        ));
        tbRelBolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelBoloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelBolo);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        rtRelBolo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtRelBolo.setText("Relatório de Bolos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtRelBolo)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtRelBolo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        lisTab();
    }//GEN-LAST:event_formWindowActivated

    private void tbRelBoloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelBoloMouseClicked
        selecTab();
    }//GEN-LAST:event_tbRelBoloMouseClicked

    public void lisTab(){
        DefaultTableModel modTab = (DefaultTableModel) tbRelBolo.getModel();
        int posLin = 0;
        modTab.setRowCount(posLin);
      
        for(Bolo b : gb.getBdBolo()){
            modTab.insertRow(posLin, new Object[]{b.getNome(), b.getPreco(), b.getSabor(), b.getPeso(), b.getTipoCobertura()});
            posLin++;
        }
    }
    
    public void selecTab(){
        int posLin = tbRelBolo.getSelectedRow();
        if (posLin >= 0) {
            String valLin = 
                "Nome: " + tbRelBolo.getValueAt(posLin, 0) + "\n" +
                "Preço: " + tbRelBolo.getValueAt(posLin, 1) + "\n" +
                "Sabor: " + tbRelBolo.getValueAt(posLin, 2) + "\n" +
                "Peso por fatia: " + tbRelBolo.getValueAt(posLin, 3) + "\n" +
                "Cobertura: " + tbRelBolo.getValueAt(posLin, 4);

            JOptionPane.showMessageDialog(null, valLin, "Dados Selecionados", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void sair(){
       int resp = JOptionPane.showConfirmDialog(
               null,
               "Deseja realmente sair?",
               "Siada do sistema",
               JOptionPane.YES_NO_OPTION
       ); 
       if (resp == 0){
           dispose();
       }
    } // fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelBolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelBolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelBolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelBolo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelBolo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtRelBolo;
    private javax.swing.JTable tbRelBolo;
    // End of variables declaration//GEN-END:variables
}
