// Aluno : Nuno Guerra - RA : a2706504
import java.util.Set;
import javax.swing.JOptionPane;


public class FormCadastroSalgado extends javax.swing.JFrame {
    private Salgado s1 = new Salgado();
    private BdProdutos gs = BdProdutos.geraBdProdutos();
    private BdItens gp = BdItens.geraGerProdutos();
    private static FormCadastroSalgado cadSalgUnic;
    
    private FormCadastroSalgado() {
        initComponents();
    }
    
    // Método Singleton
    public static FormCadastroSalgado geraCadSalg(){
        if(cadSalgUnic == null){
            cadSalgUnic = new FormCadastroSalgado();
        }
        return cadSalgUnic;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCadastroSalgado = new javax.swing.JLabel();
        rtNome = new javax.swing.JLabel();
        rtPreco = new javax.swing.JLabel();
        rtTipo = new javax.swing.JLabel();
        rtAssadoFrito = new javax.swing.JLabel();
        rtRecheio = new javax.swing.JLabel();
        cxRecheio = new javax.swing.JTextField();
        cxAssadoFrito = new javax.swing.JTextField();
        cxTipo = new javax.swing.JTextField();
        cxPreco = new javax.swing.JTextField();
        cxNome = new javax.swing.JTextField();
        btSair = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterarPreco = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtCadastroSalgado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtCadastroSalgado.setText("Cadastro Salgado");

        rtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtNome.setText("NOME..................... :");

        rtPreco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtPreco.setText("PREÇO.................... :");

        rtTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtTipo.setText("TIPO........................ :");

        rtAssadoFrito.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtAssadoFrito.setText("ASSADO OU FRITO :");

        rtRecheio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtRecheio.setText("RECHEIO................. :");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterarPreco.setText("Alterar Preço");
        btAlterarPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarPrecoActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rtRecheio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rtAssadoFrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cxAssadoFrito, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxTipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxPreco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(rtCadastroSalgado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterarPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtCadastroSalgado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPreco)
                    .addComponent(cxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTipo)
                    .addComponent(cxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtAssadoFrito)
                    .addComponent(cxAssadoFrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtRecheio)
                    .addComponent(cxRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(btConsultar)
                    .addComponent(btAlterarPreco)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        insSalg();
    }//GEN-LAST:event_btInserirActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultSalg();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarPrecoActionPerformed
        alterarPreco();
    }//GEN-LAST:event_btAlterarPrecoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirSalg();
    }//GEN-LAST:event_btExcluirActionPerformed

    public void excluirSalg(){
        s1 = new Salgado();
        
        s1.setNome(cxNome.getText());
        
        s1 = gs.delSalg(s1);
        
        if(s1 == null){
            JOptionPane.showMessageDialog(
                    null,
                    "Salgado apagado com sucesso!",
                    "Exclusão de salgado",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Nome do salgado não encontrado!",
                    "Exclusão de salgado",
                    JOptionPane.ERROR_MESSAGE
            );
            cxNome.setText("");
            cxNome.requestFocus();
        }
    } 
    
    public void alterarPreco(){
        s1 = new Salgado();
        
        s1.setNome(cxNome.getText());
        
        s1 = gs.atualizaPrecoSalg(s1);
        
        if(s1 != null){
            cxNome.setText(s1.getNome());
            cxPreco.setText(Float.toString(s1.getPreco()));
            cxTipo.setText(s1.getTipo());
            cxAssadoFrito.setText(s1.getAssadoFrito());
            cxRecheio.setText(s1.getRecheio());
            
            JOptionPane.showMessageDialog(
                    null,
                    "Salgado encontrado, verifique os dados :",
                    "Alteração de Salgado",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Nome do Salgado não encontrado!",
                    "Alteração de preço",
                    JOptionPane.ERROR_MESSAGE
            );
            cxNome.setText("");
            cxNome.requestFocus();
        }
    } // fim alterarPreco
    
    public void consultSalg(){
        s1 = new Salgado();
        
        s1.setNome(cxNome.getText());
        
        s1 = gs.consSalg(s1);
        
        if(s1 != null){
            cxNome.setText(s1.getNome());
            cxPreco.setText(Float.toString(s1.getPreco()));
            cxTipo.setText(s1.getTipo());
            cxAssadoFrito.setText(s1.getAssadoFrito());
            cxRecheio.setText(s1.getRecheio());
            
            JOptionPane.showMessageDialog(
                    null,
                    "Confirme os dados!",
                    "Consulta de Salgado",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Não existe um salgado com esse nome!",
                    "Consulta de Salgado",
                    JOptionPane.ERROR_MESSAGE
            ); 
            cxNome.setText("");
            cxNome.requestFocus();
        } 
    }
    
    public void insSalg(){
       s1 = new Salgado();
       
       s1.setNome(cxNome.getText());
       s1.setPreco(Float.parseFloat(cxPreco.getText()));
       s1.setTipo(cxTipo.getText());
       s1.setAssadoFrito(cxAssadoFrito.getText());
       s1.setRecheio(cxRecheio.getText());
       
       s1 = gs.insSalg(s1);
       s1 = (Salgado) gp.insProd(s1);
       
       if(s1 != null){
            JOptionPane.showMessageDialog(
                    null,
                    "Salgado cadastrado com sucesso!",
                    "Cadastro de Salgado",
                    1
            );
            limpar();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "ERRO : Já existe um salgado com esse nome!",
                    "Cadastro de Salgado",
                    JOptionPane.ERROR_MESSAGE
            );
            cxNome.setText("");
            cxNome.requestFocus();
        } 
        
    }
    
    public void limpar(){
        cxNome.setText("");
        cxPreco.setText("");
        cxTipo.setText("");
        cxAssadoFrito.setText("");
        cxRecheio.setText("");
        cxNome.requestFocus();
    }
    
    public void sair(){
       int resp = JOptionPane.showConfirmDialog(
               null,
               "Deseja realmente sair?",
               "Siada do sistema",
               JOptionPane.YES_NO_OPTION
       ); 
       if (resp == 0){
           dispose();
       }
    } // fim sair
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSalgado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSalgado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSalgado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastroSalgado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastroSalgado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarPreco;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAssadoFrito;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPreco;
    private javax.swing.JTextField cxRecheio;
    private javax.swing.JTextField cxTipo;
    private javax.swing.JLabel rtAssadoFrito;
    private javax.swing.JLabel rtCadastroSalgado;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtPreco;
    private javax.swing.JLabel rtRecheio;
    private javax.swing.JLabel rtTipo;
    // End of variables declaration//GEN-END:variables
}
